# General configuration.
title: Error Prone Support
logo: assets/images/favicon.svg
url: https://error-prone.picnic.tech
description: >-
  Error Prone extensions: extra bug checkers and a large battery of Refaster
  rules.

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Files and directories not to be deployed through GitHub pages.
exclude:
  - bug-pattern.mustache
  - Gemfile
  - Gemfile.lock
  - index.mustache
  - generate-docs.rb
  - README.md
  - refaster-rule-collection.mustache
  - vendor

# See https://jekyllrb.com/docs/permalinks/#built-in-formats.
permalink: pretty

# Theme configuration.
search_enabled: true
heading_anchors: true

callouts:
  summary:
    title: Summary
    color: blue
  warning:
    title: Warning
    color: red

# Theme (just-the-docs) configuration.
# See
# https://just-the-docs.github.io/just-the-docs/docs/navigation-structure/#external-navigation-links.
nav_external_links:
  - title: Error Prone Support on GitHub
    url: https://github.com/PicnicSupermarket/error-prone-support
    hide_icon: false

twitter:
  username: picnic
  card: summary

# SEO configuration.
# See https://jekyll.github.io/jekyll-seo-tag/usage.
social:
  name: Picnic
  links:
    - https://github.com/PicnicSupermarket
    - https://twitter.com/picnic
    - https://www.linkedin.com/company/picnictechnologies
