name: Update `error-prone.picnic.tech` website content
on:
  pull_request:
  push:
    branches: [ master, website ]
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
      - uses: ruby/setup-ruby@v1.118.0
        with:
          working-directory: ./website
          bundler-cache: true
      - name: Configure Github Pages
        uses: actions/configure-pages@v2.1.2
      - name: Set up JDK
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17.0.4
          distribution: temurin
          cache: maven
      - name: Compile project and extract data
        # XXX: Remove `-Dverification.{skip|warn}` and update `website/README.md`
        # once module `docgen` has no errors.
        run: |
          mvn -T1C clean install -DskipTests -Dverification.skip -Dverification.warn
          mvn -T1C clean install -DskipTests -Dverification.skip -Dverification.warn -Pdocgen
      - name: Generate documentation
        working-directory: ./website
        run: bundle exec ruby generate-docs.rb
      - name: Upload website as artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: ./website/_site
  deploy:
    if: github.ref == 'refs/heads/website'
    needs: build
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.2
